//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartasCredito.ConversionMonedaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/CartaCredito/CartaCreditoTools/BPELTools", ConfigurationName="ConversionMonedaService.BPELTools")]
    public interface BPELTools {
        
        // CODEGEN: Generating message contract since the operation process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="process", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CartasCredito.ConversionMonedaService.processResponse1 process(CartasCredito.ConversionMonedaService.processRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="process", ReplyAction="*")]
        System.Threading.Tasks.Task<CartasCredito.ConversionMonedaService.processResponse1> processAsync(CartasCredito.ConversionMonedaService.processRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/CartaCredito/CartaCreditoTools/BPELTools")]
    public partial class process : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string p_USER_CONVERSION_TYPEField;
        
        private System.Nullable<System.DateTime> p_CONVERSION_DATEField;
        
        private bool p_CONVERSION_DATEFieldSpecified;
        
        private string p_FROM_CURRENCYField;
        
        private string p_TO_CURRENCYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string P_USER_CONVERSION_TYPE {
            get {
                return this.p_USER_CONVERSION_TYPEField;
            }
            set {
                this.p_USER_CONVERSION_TYPEField = value;
                this.RaisePropertyChanged("P_USER_CONVERSION_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> P_CONVERSION_DATE {
            get {
                return this.p_CONVERSION_DATEField;
            }
            set {
                this.p_CONVERSION_DATEField = value;
                this.RaisePropertyChanged("P_CONVERSION_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_CONVERSION_DATESpecified {
            get {
                return this.p_CONVERSION_DATEFieldSpecified;
            }
            set {
                this.p_CONVERSION_DATEFieldSpecified = value;
                this.RaisePropertyChanged("P_CONVERSION_DATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string P_FROM_CURRENCY {
            get {
                return this.p_FROM_CURRENCYField;
            }
            set {
                this.p_FROM_CURRENCYField = value;
                this.RaisePropertyChanged("P_FROM_CURRENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string P_TO_CURRENCY {
            get {
                return this.p_TO_CURRENCYField;
            }
            set {
                this.p_TO_CURRENCYField = value;
                this.RaisePropertyChanged("P_TO_CURRENCY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/CartaCredito/CartaCreditoTools/BPELTools")]
    public partial class processResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> x_CONVERSION_RATEField;
        
        private bool x_CONVERSION_RATEFieldSpecified;
        
        private string x_MNS_ERRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> X_CONVERSION_RATE {
            get {
                return this.x_CONVERSION_RATEField;
            }
            set {
                this.x_CONVERSION_RATEField = value;
                this.RaisePropertyChanged("X_CONVERSION_RATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool X_CONVERSION_RATESpecified {
            get {
                return this.x_CONVERSION_RATEFieldSpecified;
            }
            set {
                this.x_CONVERSION_RATEFieldSpecified = value;
                this.RaisePropertyChanged("X_CONVERSION_RATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string X_MNS_ERROR {
            get {
                return this.x_MNS_ERRORField;
            }
            set {
                this.x_MNS_ERRORField = value;
                this.RaisePropertyChanged("X_MNS_ERROR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/CartaCredito/CartaCreditoTools/BPELTools", Order=0)]
        public CartasCredito.ConversionMonedaService.process process;
        
        public processRequest() {
        }
        
        public processRequest(CartasCredito.ConversionMonedaService.process process) {
            this.process = process;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/CartaCredito/CartaCreditoTools/BPELTools", Order=0)]
        public CartasCredito.ConversionMonedaService.processResponse processResponse;
        
        public processResponse1() {
        }
        
        public processResponse1(CartasCredito.ConversionMonedaService.processResponse processResponse) {
            this.processResponse = processResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BPELToolsChannel : CartasCredito.ConversionMonedaService.BPELTools, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BPELToolsClient : System.ServiceModel.ClientBase<CartasCredito.ConversionMonedaService.BPELTools>, CartasCredito.ConversionMonedaService.BPELTools {
        
        public BPELToolsClient() {
        }
        
        public BPELToolsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BPELToolsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BPELToolsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BPELToolsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CartasCredito.ConversionMonedaService.processResponse1 CartasCredito.ConversionMonedaService.BPELTools.process(CartasCredito.ConversionMonedaService.processRequest request) {
            return base.Channel.process(request);
        }
        
        public CartasCredito.ConversionMonedaService.processResponse process(CartasCredito.ConversionMonedaService.process process1) {
            CartasCredito.ConversionMonedaService.processRequest inValue = new CartasCredito.ConversionMonedaService.processRequest();
            inValue.process = process1;
            CartasCredito.ConversionMonedaService.processResponse1 retVal = ((CartasCredito.ConversionMonedaService.BPELTools)(this)).process(inValue);
            return retVal.processResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CartasCredito.ConversionMonedaService.processResponse1> CartasCredito.ConversionMonedaService.BPELTools.processAsync(CartasCredito.ConversionMonedaService.processRequest request) {
            return base.Channel.processAsync(request);
        }
        
        public System.Threading.Tasks.Task<CartasCredito.ConversionMonedaService.processResponse1> processAsync(CartasCredito.ConversionMonedaService.process process) {
            CartasCredito.ConversionMonedaService.processRequest inValue = new CartasCredito.ConversionMonedaService.processRequest();
            inValue.process = process;
            return ((CartasCredito.ConversionMonedaService.BPELTools)(this)).processAsync(inValue);
        }
    }
}
